title: Bootstrap Icons
baseurl: ""

markdown: kramdown

current_version: "4.3.1"
docs_version:    "4.3"
repo:            "https://github.com/twbs/bootstrap"
twitter:         "getbootstrap"
slack:           "https://bootstrap-slack.herokuapp.com"
blog:            "https://blog.getbootstrap.com"
expo:            "https://expo.getbootstrap.com"
icons:           "https://icons.getbootstrap.com"
themes:          "https://themes.getbootstrap.com"
